theme = "catppuccin_mocha"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
true-color = true # fix colors when using ssh/tmux https://github.com/helix-editor/helix/discussions/6963#discussioncomment-5805791

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
